import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import eslintConfigPrettier from 'eslint-config-prettier'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  // Build and tooling output. `coverage/` is generated by
  // `npm run test:coverage` and contains a bundled HTML report whose
  // vendored scripts ESLint would otherwise lint — three warnings about
  // somebody else's code, appearing only on machines that have run
  // coverage, which is the kind of noise that trains people to ignore lint.
  { ignores: ['dist', 'coverage'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // AGENTS.md: "No `any` without an inline justification comment."
      // Kept as `error` so a bare `any` fails the build; use
      // `// eslint-disable-next-line @typescript-eslint/no-explicit-any -- reason`
      // when one is genuinely unavoidable.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  eslintConfigPrettier,
)
