<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Whether the second factor is in force at all
    |--------------------------------------------------------------------------
    |
    | AGENTS.md: "MFA is required for Super Admin and Finance roles in Phase 1
    | — these roles can move money and change rates." ADR-0008 is the decision
    | behind it. Neither is repealed by this switch.
    |
    | What this is for is development. The seeded Finance and Super Admin
    | accounts carry a known TOTP secret, so every sign-in as either of them
    | costs a code generated by hand — which is the right friction against a
    | real fleet's money and pure tax on somebody building a screen.
    |
    | Off, the platform stops *demanding* enrolment and stops *challenging*
    | for a code. It does not delete anybody's secret, so turning it back on
    | restores exactly the accounts that were protected before, with the same
    | secrets and the same recovery codes.
    |
    | **It cannot be switched off in production.** See
    | App\Support\Auth\MfaRequirement: the environment is checked before this
    | value is read, so a stray MFA_ENABLED=false in a production .env does
    | nothing at all. A switch that could disable the second factor on a live
    | fleet by way of a copied env file would be worse than no switch.
    |
    */

    'enabled' => (bool) env('MFA_ENABLED', true),

];
