<?php

/**
 * The vehicle-silhouette census.
 *
 * **This exists because the worklog has already recorded the bill twice.**
 * `Vehicle::CATEGORIES` is mirrored by hand across six places, and the census
 * taken on 2026-08-21 found two of them stale — including a driver sign-up
 * form that did not offer `boda`, on a platform whose stated reason for
 * existing is that most drivers here own the boda they ride. That entry's own
 * conclusion: *"A hand-mirrored list drifts, and this one drifted within 48
 * hours of its most recent copy being made."*
 *
 * Drawing the driver's own vehicle on the driver's own map added a seventh
 * copy — `mobile/src/trips/vehicleSprites.ts`, which carries both the mapping
 * table and the artwork, because a React Native bundle cannot import from the
 * console's `public/` and an inline WebView document has no asset loader in
 * front of it. A comment asking the next reader to keep it in step is exactly
 * what was there last time, so this is a test instead.
 *
 * It censuses the *silhouette* copies specifically — the category list is
 * covered by the resource and form tests. Three claims:
 *
 * 1. every category the fleet can hold maps to a silhouette somewhere;
 * 2. the console and the driver app agree with the server about which;
 * 3. the driver app's inlined SVGs are the console's assets byte for byte.
 *
 * A repository-relative read is the point rather than a smell. All three apps
 * live here and CI checks out all of them; a census that could not see the
 * copies would not be one.
 */

use Modules\Fleet\Controllers\PublicNearbyVehicleController;
use Modules\Vehicles\Models\Vehicle;

/** A file from the repository root, which is one level above `backend/`. */
function repoFile(string $relative): string
{
    $path = base_path('../'.$relative);

    // Thrown rather than skipped, deliberately. A guard that quietly stands
    // down when the thing it guards has moved is a guard that stopped biting
    // without telling anybody — the failure mode this whole suite exists to
    // close.
    expect(file_exists($path))->toBeTrue("Missing censused file: {$relative}");

    return file_get_contents($path);
}

/** The server's own category → silhouette table, which is the reference. */
function serverSpriteMap(): array
{
    $reflected = new ReflectionClass(PublicNearbyVehicleController::class);

    return $reflected->getConstant('KINDS');
}

/**
 * A `{ key: 'value' }` table lifted out of a TypeScript source file.
 *
 * Parsed rather than executed: neither app's build is available here, and the
 * shape being censused is a flat literal in both files. A table that stops
 * being a flat literal fails the assertion rather than passing silently,
 * which is the correct outcome — it means the copy has changed shape and
 * somebody has to look at it.
 */
function typescriptTable(string $source, string $declaration): array
{
    // `\R` and an optional semicolon, because the two apps do not write
    // TypeScript the same way: the console omits statement semicolons and the
    // driver app keeps them, and both files are CRLF in this checkout.
    $pattern = '/'.preg_quote($declaration, '/').'[^=]*=\s*\{(.*?)\R\};?/s';

    expect(preg_match($pattern, $source, $block))->toBe(1, "Could not find {$declaration}");

    preg_match_all("/'?([a-z_]+)'?\s*:\s*'([a-z_]+)'/", $block[1], $rows, PREG_SET_ORDER);

    return collect($rows)->mapWithKeys(fn ($row) => [$row[1] => $row[2]])->all();
}

it('maps every category the fleet can actually hold', function () {
    // The `boda` case, generalised. A category an operator can pick that no
    // table knows about falls through to `sedan` everywhere — a rider's
    // machine drawn as a saloon on the one screen that rider looks at.
    $mapped = array_keys(serverSpriteMap());

    expect(array_diff(Vehicle::CATEGORIES, $mapped))->toBe([]);
});

it('keeps the console and the driver app in step with the server', function () {
    $server = serverSpriteMap();

    $console = typescriptTable(
        repoFile('frontend/src/lib/livePositions.ts'),
        'const SPRITE_KINDS',
    );

    $driverApp = typescriptTable(
        repoFile('mobile/src/trips/vehicleSprites.ts'),
        'const SPRITE_KINDS',
    );

    expect($console)->toBe($server);
    expect($driverApp)->toBe($server);
});

it('keeps the driver app drawing the console artwork byte for byte', function () {
    // "Transcribed verbatim" is DESIGN.md §7's demand of Lucide paths, for the
    // reason it gives: two apps drawing *nearly* the same shape is the drift
    // nobody ever notices. The driver app's copy is generated by reading these
    // files, and this is what keeps that true after somebody edits one.
    $bundle = repoFile('mobile/src/trips/vehicleSprites.ts');

    $files = [
        'sedan' => 'sedan-top.svg',
        'suv' => 'suv-top.svg',
        'pickup' => 'pickup-top.svg',
        'boda' => 'boda-rider-top.svg',
    ];

    foreach ($files as $sprite => $file) {
        $artwork = trim(repoFile('frontend/public/assets/vehicles/'.$file));

        // `str_contains` rather than `toContain`, which is variadic: a second
        // argument to it is another needle, not the message it looks like.
        expect(str_contains($bundle, $artwork))
            ->toBeTrue("The driver app's {$sprite} sprite has drifted from {$file}");
    }
});
