import type { CSSProperties, HTMLAttributes } from 'react'
import { ICON_REGISTRY } from './iconRegistry'

/**
 * Ported from `KangaruRide Design System/components/core/Icon.jsx`. The
 * original reads `window.lucide.icons` (CDN UMD global) since the design
 * system's browser preview harness has no bundler.
 *
 * This reads a generated registry rather than lucide-react's `icons`
 * dictionary. Same lookup, same API — but `icons` is a runtime object no
 * bundler can tree-shake, so importing it shipped all 1756 Lucide icons
 * (467,925 bytes, 34% of the main chunk) to render the 126 this app names.
 * `tools/generate-icon-registry.mjs` rebuilds the registry; run it after
 * introducing an icon name that is not already in use.
 */
/**
 * "MapPin" | "map_pin" -> "map-pin". Kebab names pass through unchanged.
 *
 * The digit rules are not incidental: Lucide names `Building2` as
 * `building-2`, so a transform that only breaks on case produces `building2`
 * and misses the icon. That failure is silent — the lookup below falls back
 * to a grey box rather than throwing.
 */
function toKebab(name: string): string {
  return name
    .replace(/_/g, '-')
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .replace(/([0-9])([a-zA-Z])/g, '$1-$2')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

export interface IconProps extends HTMLAttributes<HTMLSpanElement | SVGSVGElement> {
  /** Lucide icon name, kebab or Pascal case: "truck", "map-pin", "MapPin". */
  name: string
  /** Pixel box. 16 in dense tables, 20 default, 24 for nav. */
  size?: number
  /** Lucide default is 2; use 1.5 only at 24px+. */
  strokeWidth?: number
  /** Defaults to currentColor — colour comes from the parent. */
  color?: string
  /** Provide only when the icon is the sole label; otherwise leave undefined (decorative). */
  title?: string
  style?: CSSProperties
}

export function Icon({
  name,
  size = 20,
  strokeWidth = 2,
  color = 'currentColor',
  title,
  style,
  ...rest
}: IconProps) {
  const LucideIcon = ICON_REGISTRY[name] ?? ICON_REGISTRY[toKebab(name)]
  const box: CSSProperties = {
    width: size,
    height: size,
    display: 'inline-block',
    flex: '0 0 auto',
    verticalAlign: 'middle',
  }

  if (!LucideIcon) {
    /*
     * The placeholder below is a grey box, which is indistinguishable from a
     * deliberate spacer to anyone looking at the screen. Since the registry is
     * generated by scanning source for string literals, a name assembled at
     * runtime — or one added without rerunning the generator — falls through
     * here and simply looks slightly wrong forever. Say so while developing.
     */
    if (import.meta.env.DEV) {
      console.warn(
        `[Icon] "${name}" is not in the generated registry, so it renders as a placeholder. ` +
          `Run \`node tools/generate-icon-registry.mjs\` if the name is new; if it is built at ` +
          `runtime rather than written as a literal, add it to the generator's seed list.`,
      )
    }
    return (
      <span
        aria-hidden="true"
        style={{ ...box, borderRadius: 2, background: 'currentColor', opacity: 0.18, ...style }}
        {...rest}
      />
    )
  }

  return (
    <LucideIcon
      size={size}
      strokeWidth={strokeWidth}
      color={color}
      role={title ? 'img' : 'presentation'}
      aria-hidden={title ? undefined : 'true'}
      aria-label={title}
      style={{ ...box, ...style }}
      {...rest}
    />
  )
}
