import type { DispatchOffer } from '../api/types';
import { buildCallContent, callNotificationId, OFFER_ACTION } from './callContent';
import { OFFER_CALL_CHANNEL_ID } from './channels';
import { loadNotifyKit } from './notifyKit';

/**
 * The incoming-call screen for a job offer (ADR-0049 §3).
 *
 * This is the piece ADR-0046 §6 deliberately left for later, and the answer to
 * *"the popup does not come"*: nothing in the app had ever asked Android to
 * launch anything. A MAX-importance channel buys a heads-up **banner** — a
 * strip at the top of a lock screen that a driver has to notice, read and tap.
 * A full-screen intent is a different mechanism entirely: it tells Android to
 * start an activity, which is why a WhatsApp call takes over a locked phone
 * instead of sitting in a strip. `expo-notifications` cannot set one.
 *
 * ## The precondition, stated plainly because everything rests on it
 *
 * **Something has to be alive to call this.** A full-screen intent is set by
 * whoever builds the notification, and here that is JavaScript — so the
 * process must exist at the moment the offer arrives.
 *
 * ADR-0046 §1 is what makes that true, and it is the reason the foreground
 * service was called the keystone: while *"You are online"* is on,
 * `Location.startLocationUpdatesAsync` holds an ongoing service, the process
 * stays alive, and the app's JavaScript keeps running with the app closed and
 * the screen dark. The owner's own framing of this feature — *"provided the
 * driver has internet and has enabled You are online"* — is exactly that
 * precondition, arrived at from the other direction.
 *
 * Off duty, none of this runs, and nothing is sent: the matcher does not
 * offer to drivers who are off.
 *
 * ## Why it does not replace the push notification
 *
 * `offers.v2` still delivers, still rings, still shows its banner. That is the
 * floor, and it is the only thing that works if an OEM battery manager has
 * killed the service — the failure ADR-0046 records as unsolvable in code on
 * the Tecno, Infinix and Xiaomi handsets this fleet runs.
 *
 * So this is an **upgrade applied on arrival**, not a replacement: the push
 * makes the noise, and if the app is there to hear it, the app puts a call
 * screen in front of the driver. Two notifications never ring at once because
 * `OFFER_CALL_CHANNEL_ID` is silent by construction — see the argument on the
 * channel itself.
 */

/**
 * Brand green, as Android wants it.
 *
 * `colors.primary` from the theme, written out rather than imported: this
 * module is reached from a background handler that may run before any React
 * tree exists, and `theme.ts` imports from `react-native` at module scope.
 * One hex string is a cheaper dependency than a launch-path import.
 */
/**
 * Marks a notification as the call screen rather than the plain push.
 *
 * Both rows name the same offer, so the id alone cannot separate them. This is
 * the one field that can — see the `data` block in `showCallNotification`, and
 * the filter in `dismissPlainPush` that reads it.
 */
export const CALL_SURFACE = 'call';

const ACCENT = '#01903D';

/**
 * The monochrome icon Android draws in the status bar.
 *
 * **Generated by the `expo-notifications` config plugin**, from the `icon`
 * option in `app.json` — the plugin writes it to `res/drawable/` under exactly
 * this name (`NOTIFICATION_ICON` in `withNotificationsAndroid.js`). Naming it
 * here is what stops the call notification showing a grey square where every
 * other notification in the app shows the kangaroo.
 *
 * It is a cross-library dependency and nothing checks it: notify-kit does not
 * generate this resource and expo-notifications does not know notify-kit
 * exists. If the `icon` option is ever removed from that plugin, this string
 * stops resolving and the icon silently degrades.
 */
const SMALL_ICON = 'notification_icon';

/**
 * Puts the offer in front of the driver, over the lock screen.
 *
 * Idempotent on the offer: the notification's id is derived from it, so a
 * second push for the same job — a retry, a duplicate wave — replaces the
 * notification rather than stacking a second one behind it.
 *
 * Does nothing on iOS, in Expo Go, on a simulator, or when the offer has no
 * window left. All four are ordinary and none is an error a driver could act
 * on.
 *
 * ## Why it returns whether it posted, and why that is not a nicety
 *
 * **Because the caller withdraws the server's push on the strength of this.**
 * `raiseOfferCall` takes the plain `offers.v2` notification down the moment
 * the answerable one is up, so one job is one row.
 *
 * While this returned `void`, every one of the four ordinary no-ops above was
 * indistinguishable from success — so the caller dismissed the floor for an
 * upgrade that had not happened, and the driver was left with **nothing**: a
 * ring that started, a screen that woke, and an empty notification shade by
 * the time they had the phone in their hand.
 *
 * That is the failure this codebase keeps re-learning: silence that means
 * "fine" and silence that means "broken" must not be the same silence.
 */
export async function showCallNotification(offer: DispatchOffer): Promise<boolean> {
  const content = buildCallContent(offer);

  if (content === null) {
    console.warn('offer.call_not_shown', offer.id, 'no_window_left');

    return false;
  }

  const notifee = await loadNotifyKit();

  if (notifee === null) {
    // iOS, Expo Go, a simulator, or a build without the native module. The
    // driver keeps the plain push — which is why the caller must not remove
    // it, and why this says so rather than returning quietly.
    console.warn('offer.call_not_shown', offer.id, 'no_notify_kit');

    return false;
  }

  const { AndroidCategory, AndroidImportance, AndroidVisibility } = await import(
    'react-native-notify-kit'
  );

  try {
    await notifee.displayNotification({
      id: content.id,
      title: content.title,
      body: content.body,

      // **The same key the push payload uses**, so a handler that is given
      // either one reads the offer out the same way. `routing.ts` parses
      // `offer_id` from a push; this keeps the call notification speaking
      // that vocabulary rather than inventing a second one.
      //
      // A string, because Android stringifies notification extras on some
      // versions and a handler that expected a number would work in
      // development and fail on a driver's handset. `routing.ts` already
      // accepts both for exactly this reason.
      //
      // **`surface` is what stops this notification cancelling itself.**
      // `dismissPlainPush` finds the row to withdraw by the offer it names,
      // and this row names the same offer — so without a way to tell the two
      // apart it matched, and the call screen was dismissed by the very
      // function that runs immediately after raising it. The symptom is the
      // one a driver reported: the phone rings, the screen wakes, and there
      // is nothing to answer by the time they look. Found in logcat as a
      // cancel 1.7s after `offer.push_task` reported `open_offer`.
      //
      // A marker in `data` rather than a channel comparison because the
      // presented-notification shape Expo returns does not carry the Android
      // channel on every version, and a filter that silently stops matching
      // would bring the bug straight back.
      data: { offer_id: String(content.offerId), surface: CALL_SURFACE },

      android: {
        channelId: OFFER_CALL_CHANNEL_ID,
        smallIcon: SMALL_ICON,
        color: ACCENT,

        // **The line that makes this a call and not a banner.** Android
        // starts the activity instead of posting a heads-up, which — with
        // `showWhenLocked` and `turnScreenOn` from `withLockScreenCallUi` —
        // wakes a dark phone and draws the offer in front of the keyguard.
        //
        // Note the degradation, because it is silent and it is the thing to
        // check first when this appears not to work: without the
        // `USE_FULL_SCREEN_INTENT` permission Android does not refuse, it
        // quietly posts a heads-up notification instead. On Android 14 and up
        // that permission is not granted at install (see
        // `fullScreenIntent.ts`), so a driver who has not granted it gets the
        // banner and no error anywhere.
        fullScreenAction: { id: OFFER_ACTION.open, launchActivity: 'default' },

        // Tapping the body, as opposed to a button. Same destination.
        pressAction: { id: OFFER_ACTION.open, launchActivity: 'default' },

        // Wakes a dark screen even where the full-screen intent is downgraded
        // to a banner. Cheap, and it is what a driver with a phone face-down
        // on a cradle actually needs.
        lightUpScreen: true,

        // **Rings for the whole window, not once.** A notification tone plays
        // for a second and stops; a call rings until it is answered or gives
        // up, and that difference is most of why a driver notices one and not
        // the other. The loop is bounded by `timeoutAfter` below — it cannot
        // outlive the offer — and by every path that cancels this
        // notification, since cancelling stops the sound with it.
        //
        // This is why the channel had to move to `offers.call.v2`: the sound
        // is the channel's, and `v1` was created without one.
        loopSound: true,

        // The kangaroo, in the slot a calling app puts the caller's face. It
        // is what makes this read as *KangaruRide is calling you* at a glance
        // rather than as one more row in the shade. The same asset the
        // launcher uses, so nothing extra is bundled for it.
        largeIcon: require('../../assets/icon.png'),

        // Not swipeable and not dismissed by a tap. An offer is answered or it
        // expires; a driver who brushed it off the lock screen and then wanted
        // it back would have no way to get it, and `timeoutAfter` below is
        // what actually removes it.
        ongoing: true,
        autoCancel: false,

        // **Never re-alerts.** A replacement for the same offer must not buzz
        // the handset again — and it must never re-fire the full-screen
        // intent, which would yank the driver back to the top of the offer
        // screen mid-read.
        onlyAlertOnce: true,

        // The offer's own window plus a small grace. This is the guarantee
        // that a dead job does not sit on a lock screen: even if every other
        // path forgets, Android removes it. Argued in `callContent.ts`.
        timeoutAfter: content.timeoutMs,

        // What Android uses to decide this is call-like — it is what earns the
        // treatment on OEM skins and what keeps it visible under some Do Not
        // Disturb configurations.
        category: AndroidCategory.CALL,

        // HIGH, matching the channel. Importance on the notification cannot
        // exceed the channel's on Android 8+, so this is a statement of intent
        // rather than an override.
        importance: AndroidImportance.HIGH,

        // Readable on a locked screen, deliberately. ADR-0025 §5 made that
        // trade: a driver cannot judge a job without knowing where it starts,
        // and the payload carries no passenger identity to expose.
        visibility: AndroidVisibility.PUBLIC,

        // **Decline on the left, Accept on the right.** The same asymmetry
        // `OfferScreen` argues for, for the same reason: a mis-tapped decline
        // costs this driver a fare and costs a passenger another wait, so the
        // destructive one does not sit under the thumb.
        //
        // Neither carries `launchActivity` for the *answer* — the answer is
        // made by `offerAnswer.ts` from the press itself, so a driver who taps
        // Accept is accepted whether or not the app finishes opening. Accept
        // additionally opens the app, because a driver who just took a job
        // needs the pickup screen next and would otherwise have to find it.
        actions: [
          {
            title: 'Decline',
            pressAction: { id: OFFER_ACTION.decline },
          },
          {
            title: 'Accept',
            pressAction: { id: OFFER_ACTION.accept, launchActivity: 'default' },
          },
        ],
      },
    });


    return true;
  } catch (thrown) {
    // The offer is unaffected. It is on `GET /me/offers`, the push has already
    // rung on `offers.v2`, and the app's own overlay paints it the moment the
    // driver looks — ADR-0025 §3, one layer along.
    //
    // Reported, not swallowed: `false` keeps the caller from withdrawing the
    // plain push, and the message is the only account of a notify-kit failure
    // that will ever exist on a driver's handset.
    console.warn('offer.call_not_shown', offer.id, String(thrown));

    return false;
  }
}

/**
 * Takes the call screen down.
 *
 * Called when the job is answered, withdrawn or gone, and when the driver is
 * already looking at the offer inside the app — a notification for a screen
 * somebody is standing on is clutter, and worse, its Accept button is a second
 * way to answer a job they are already answering.
 *
 * Never throws. Cancelling a notification that is not showing is a no-op in
 * notify-kit, which is what lets callers fire this without first asking.
 */
export async function hideCallNotification(offerId: number): Promise<void> {
  const notifee = await loadNotifyKit();

  if (notifee === null) {
    return;
  }

  try {
    await notifee.cancelNotification(callNotificationId(offerId));
  } catch {
    // `timeoutAfter` is the guarantee; this is the courtesy. A cancel that
    // failed leaves a notification that Android removes on the offer's own
    // deadline anyway.
  }
}

/**
 * Takes down every call screen this app has raised.
 *
 * For the transitions where the app cannot name the offer it is clearing —
 * going off duty, signing out — and where leaving one up would be worse than
 * any of the individual cases. A driver who has signed off must not have a
 * job on their lock screen with a live Accept button on it, and a driver who
 * has signed out must not have the *previous* driver's job there (ADR-0025
 * §4).
 */
export async function hideAllCallNotifications(): Promise<void> {
  const notifee = await loadNotifyKit();

  if (notifee === null) {
    return;
  }

  try {
    const showing = await notifee.getDisplayedNotifications();

    await Promise.all(
      showing
        .filter((item) => item.id !== undefined && item.id.startsWith('offer-call-'))
        .map((item) => notifee.cancelNotification(item.id as string)),
    );
  } catch {
    // See `hideCallNotification`.
  }
}
