import type { CSSProperties, ImgHTMLAttributes } from 'react'

/*
 * The `-web` files, not the masters beside them.
 *
 * The originals are print-resolution (the navy lockup is 1659x465 and
 * 970,861 bytes) and were being served raw to render about 200px wide in the
 * sidebar, on every authenticated page load. These are the same artwork at
 * roughly 2x its largest on-screen size — 6,029,164 bytes of masters become
 * 313,188 bytes shipped, with nothing visibly different at any size the app
 * renders them.
 *
 * Generated by `tools/resize-brand-assets.mjs`. The masters stay in
 * `public/assets` for print and for regenerating these; add a new variant
 * there rather than pointing this map back at one.
 */
const FILES = {
  horizontal: 'logo-horizontal-web.png',
  'horizontal-navy': 'logo-horizontal-navy-web.png',
  stacked: 'logo-stacked-light-web.png',
  mono: 'logo-horizontal-mono-web.png',
  mark: 'logo-mark-web.png',
  'mark-solid': 'logo-mark-solid-web.png',
} as const

type Variant = keyof typeof FILES

export interface LogoProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'alt' | 'height'> {
  /**
   * horizontal      — navy/green lockup for light surfaces (default)
   * horizontal-navy — white/green lockup, for navy chrome and dark heroes
   * stacked         — mark above wordmark, for login and print
   * mono            — single-colour black lockup, for documents and faxable PDFs
   * mark            — outlined circle mark only
   * mark-solid      — solid green circle mark only, for app icons and avatars
   */
  variant?: Variant
  /** Rendered height in px. Minimum 24px for lockups, 20px for the mark. */
  height?: number
  /** Path from the consuming page to the copied assets folder (served from `public/assets`). */
  basePath?: string
  /** With a mark variant, sets the wordmark in Sora beside it (used when the sidebar is expanded). */
  withWordmark?: boolean
  style?: CSSProperties
}

export function Logo({
  variant = 'horizontal',
  height = 32,
  basePath = '/assets',
  withWordmark = false,
  style,
  ...rest
}: LogoProps) {
  const src = `${basePath}/${FILES[variant] ?? FILES.horizontal}`
  const isMark = variant.startsWith('mark')
  const img = (
    <img
      src={src}
      alt="KangaruRide"
      style={{
        height,
        width: isMark ? height : 'auto',
        display: 'block',
        objectFit: 'contain',
        ...(withWordmark ? {} : style),
      }}
      {...(withWordmark ? {} : rest)}
    />
  )
  if (!withWordmark || !isMark) return img
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 'var(--space-2)', ...style }} {...rest}>
      {img}
      <span
        style={{
          fontFamily: 'var(--font-display)',
          fontWeight: 'var(--weight-bold)',
          fontSize: Math.round(height * 0.55),
          letterSpacing: 'var(--tracking-tight)',
          color: 'inherit',
          whiteSpace: 'nowrap',
        }}
      >
        KangaruRide
      </span>
    </span>
  )
}
