/**
 * Vendors Leaflet into the driver app as a string module.
 *
 * The driver's maps are HTML documents inside a WebView, and until ADR-0070
 * each of them fetched its map library from a CDN on every mount — MapLibre
 * GL, about a megabyte, over whatever signal a Kampala boda has at the kerb.
 * That fetch was most of "the map is too slow".
 *
 * Leaflet is 160 KB and needs no WebGL. Writing it out as a TypeScript module
 * means the document builders inline it: the library is part of the app
 * bundle, loads from disk, and is there with no signal at all. Only the tiles
 * still come from the network.
 *
 * Why a generated module and not an asset: Metro bundles `.js` as code, not
 * text, and the alternatives — an asset read with `expo-file-system` on first
 * use, or a config plugin copying files into `android/app/src/main/assets` —
 * each add an asynchronous step or a build step in front of a map that has
 * to draw the moment the screen settles. A string constant has neither.
 *
 * `JSON.stringify` rather than a template literal, so nothing in a future
 * Leaflet release — a backtick, a `${` — can end the string it is written
 * into. The one thing no escaping can fix is `</script` inside the JS, which
 * would close the inline tag in the document; the build refuses that outright.
 *
 * Run from the repo root after bumping `leaflet` in mobile/package.json:
 *   node tools/vendor-leaflet.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const MOBILE = join(ROOT, 'mobile')
const OUT = join(MOBILE, 'src', 'trips', 'vendor', 'leaflet.ts')

const require_ = createRequire(join(MOBILE, 'package.json'))
const pkg = require_('leaflet/package.json')
const dist = join(dirname(require_.resolve('leaflet/package.json')), 'dist')

const js = readFileSync(join(dist, 'leaflet.js'), 'utf8')
const css = readFileSync(join(dist, 'leaflet.css'), 'utf8')

if (/<\/script/i.test(js)) {
  throw new Error('leaflet.js contains "</script" — it would close the inline tag in the map document')
}

const header = `
// GENERATED by tools/vendor-leaflet.mjs from leaflet@${pkg.version} (${pkg.license}) — do not edit.
//
// Leaflet, inlined into the driver's map documents so the library ships in the
// app bundle instead of being fetched from a CDN on every mount (ADR-0070).
// Regenerate after bumping the dependency: node tools/vendor-leaflet.mjs
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(
  OUT,
  header +
    `export const LEAFLET_VERSION = ${JSON.stringify(pkg.version)};\n` +
    `export const LEAFLET_JS = ${JSON.stringify(js)};\n` +
    `export const LEAFLET_CSS = ${JSON.stringify(css)};\n`,
)

console.log(`wrote ${OUT} (leaflet@${pkg.version}: ${js.length} B js, ${css.length} B css)`)
