import { useEffect, useMemo, useRef } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';

import { useAfterTransition } from '../navigation/useAfterTransition';
import { MAPLIBRE_CSS, MAPLIBRE_JS } from './vendor/maplibre';
import { colors, radius, spacing, typography } from '../ui/theme';

/**
 * Where the driver is, on the trip card.
 *
 * ## Why a WebView and not a native map
 *
 * `react-native-maps` was the first attempt and rendered a grey grid: Google
 * Maps needs an API key, in Expo Go and in any standalone Android build, and
 * this platform has none. Buying that key would make the driver's home screen
 * depend on a Google billing account before it can draw a street.
 *
 * MapLibre GL against CARTO's Positron style needs no key at all, and it is
 * already what the console falls back to when `VITE_MAPBOX_TOKEN` is unset
 * (`frontend/src/pages/public/MapPanel.tsx`) — so the two surfaces draw
 * Kampala the same way. The native MapLibre binding would need a development
 * build; inside a WebView it runs in Expo Go, on a physical handset, and in
 * whatever the fleet eventually installs.
 *
 * ## The library ships in the bundle, not from a CDN
 *
 * This document used to carry `<script src="unpkg.com/maplibre-gl@4.7.1">`
 * and its stylesheet — about 870 KB fetched on **every mount**, over whatever
 * signal a boda has at the kerb. The WebView cache hid that on a warm handset
 * and did nothing on a cold one, an evicted one, or the first run, which is
 * the run a new driver judges the app by. The owner, from a handset: *"I feel
 * like the Map is too slow."*
 *
 * `vendor/maplibre.ts` is that library as a string, generated by
 * `tools/vendor-maplibre.mjs` and inlined below, so it loads from the app
 * bundle with no signal at all. Only the vector tiles are still fetched.
 *
 * **A raster map would be smaller still, and ADR-0070 tried it.** Leaflet over
 * CARTO's raster tiles is a fifth of the size and needs no WebGL — but every
 * raster tile came back stamped "API KEY REQUIRED", while the *vector* style
 * this document uses is genuinely keyless, and no keyless raster basemap is
 * available to a commercial fleet. The library was the half we could fix
 * without a billing account; the renderer was not.
 *
 * ## Why it is not interactive
 *
 * It answers one question at a glance — "does the app know where I am?" —
 * which is what decides whether dispatch can offer this driver work at all
 * (ADR-0024 §2). Turn-by-turn is a different product and belongs to whatever
 * app the driver already trusts for it. Gestures are off so the map cannot
 * steal the scroll from the card it sits in.
 *
 * ## Why the pin is the driver and not the route
 *
 * Not because the platform lacks the coordinates — it has had them since
 * `TripResource` grew `pickup`/`dropoff` places, and `PickupMap` draws the
 * route (road-real when `GET /trips/{trip}/route` answers, dashed otherwise).
 * This map answers a different question: the home card's glance is "does the
 * app know where I am", and the trip's geography belongs to the trip screens.
 * The pin is the real fix `DriverPresence` reports, and when there is none
 * the component says so rather than centring on a plausible-looking nowhere.
 */
export function TripMap({
  latitude,
  longitude,
  stale,
}: {
  latitude: number | null;
  longitude: number | null;
  /** The fix is too old for the matcher to act on (ADR-0024 §2). */
  stale?: boolean;
}) {
  const webRef = useRef<WebView>(null);

  // The map waits for the screen to finish arriving before it mounts
  // (`useAfterTransition`): a WebView mounting mid-push is the stutter the
  // owner reported. Answers `true` at once when there is no stack around it.
  const settled = useAfterTransition();

  // The latest fix, held where the load handler can read it without being in
  // the document's dependency list. Written in an effect rather than during
  // render — a ref assigned in the render body is invisible to the React
  // Compiler, which then cannot memoise this component at all.
  const positionRef = useRef(
    latitude === null || longitude === null ? null : [longitude, latitude],
  );

  useEffect(() => {
    positionRef.current = latitude === null || longitude === null ? null : [longitude, latitude];
    // A new fix is one marker gliding, not a page rebuilding. The document
    // used to be rebuilt on every position change, and a changed
    // `source.html` makes the WebView reload the whole page — white flash,
    // tiles refetched — on a card whose position now refreshes with every
    // presence heartbeat. `true;` because injectJavaScript evaluates the
    // string; the guard tolerates a page that has not finished loading, which
    // `onLoadEnd` below covers.
    // Optional twice over: the page may not have finished loading (`onLoadEnd`
    // below replays the fix), and the test harness mounts WebView as a bare
    // view with no bridge at all.
    webRef.current?.injectJavaScript?.(
      `window.__setPosition && window.__setPosition(${JSON.stringify(positionRef.current)}); true;`,
    );
  }, [latitude, longitude]);

  const hasFix = latitude !== null && longitude !== null;

  // Built once per gained-or-lost fix, never per movement: the document is
  // seeded from the ref and every later fix travels through the injection
  // above. Keying on the coordinates — as this used to — reloaded the page
  // each time they changed.
  const html = useMemo(
    () => (hasFix ? mapDocument([longitude as number, latitude as number]) : null),
    // eslint-disable-next-line react-hooks/exhaustive-deps -- the coordinates deliberately do not re-key the document; they seed it when it happens to build and travel via injection ever after
    [hasFix],
  );

  if (html === null) {
    return (
      <View style={styles.placeholder}>
        {/*
          **Not "dispatch cannot offer you work until your phone reports one",
          which is what this said and which is false.** A driver with no
          reported position stays in the pool — `DatabaseDriverPresenceStore::
          dispatchable()` keeps them through its `whereNull('latitude')` branch
          and `WalkInRecommender` ranks them without distance, saying so on the
          offer itself: "This driver has not reported a position, so distance
          was not used."

          Proved by running it: on an emulator that never delivered a fix, this
          message sat on the screen while the same phone was offered a ride and
          accepted it. Telling a driver they cannot be sent work while work is
          arriving is the kind of copy that teaches them to distrust the app —
          and the wording here now matches `DutyBar`'s, which was already
          honest about it being a ranking problem rather than a shutout.
        */}
        <Text style={styles.placeholderText}>
          Waiting for a location fix. Jobs can still reach you, but nearby ones may go to a driver
          whose phone has reported one.
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.frame}>
      {/* The frame keeps its size while empty, so the map landing shifts nothing. */}
      {settled && (
        <WebView
          ref={webRef}
          style={styles.web}
          originWhitelist={['*']}
          source={{ html }}
          // The fix again once the page exists: the effect above can fire before
          // the document has parsed, and an update injected into a page that is
          // not there yet is silently dropped.
          onLoadEnd={() =>
            webRef.current?.injectJavaScript?.(
              `window.__setPosition && window.__setPosition(${JSON.stringify(positionRef.current)}); true;`,
            )
          }
          // The card owns the tap; the map is a picture as far as touch goes.
          pointerEvents="none"
          scrollEnabled={false}
          showsHorizontalScrollIndicator={false}
          showsVerticalScrollIndicator={false}
          // Tiles and the library are the same bytes every time this mounts.
          cacheEnabled
          androidLayerType="hardware"
        />
      )}

      {stale === true && (
        <View style={styles.staleTag}>
          <Text style={styles.staleTagText}>Last known position</Text>
        </View>
      )}
    </View>
  );
}

/**
 * The whole map as one document.
 *
 * Inline rather than a bundled asset so there is nothing to keep in step: the
 * only inputs are two numbers and the brand green, and the style URL is the
 * same keyless CARTO one the console uses.
 */
function mapDocument(position: number[]): string {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<style>${MAPLIBRE_CSS}</style>
<style>
  html, body, #map { margin: 0; padding: 0; height: 100%; width: 100%; background: ${colors.surfaceSunken}; }
  .maplibregl-ctrl-attrib, .maplibregl-ctrl-bottom-left { display: none; }
  /* The halo is the theme's green tint, not a hand-mixed alpha — one more
     place a raw colour would have crept in unnoticed. */
  .pin {
    width: 30px; height: 30px; border-radius: 50%;
    background: ${colors.primaryTint};
    opacity: 0.92;
    display: flex; align-items: center; justify-content: center;
  }
  .pin i {
    width: 14px; height: 14px; border-radius: 50%;
    background: ${colors.primary};
    border: 2.5px solid ${colors.onPrimary};
    display: block;
  }
</style>
</head>
<body>
<div id="map"></div>
<script>${MAPLIBRE_JS}</script>
<script>
  var map = new maplibregl.Map({
    container: 'map',
    style: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
    center: ${JSON.stringify(position)},
    // ~1.5km across: close enough to recognise the junction you are at, wide
    // enough that a poor fix does not look like a wild jump.
    zoom: 14.2,
    attributionControl: false,
    interactive: false
  });

  var el = document.createElement('div');
  el.className = 'pin';
  el.innerHTML = '<i></i>';

  var marker = null;
  var pending = ${JSON.stringify(position)};
  var loaded = false;

  // The one entry point React Native injects into. A fix that arrives before
  // the style has loaded is parked and replayed from the load handler.
  window.__setPosition = function (lngLat) {
    if (lngLat === null) { return; }
    if (!loaded) { pending = lngLat; return; }

    if (marker === null) {
      marker = new maplibregl.Marker({ element: el }).setLngLat(lngLat).addTo(map);
    } else {
      marker.setLngLat(lngLat);
    }

    // Eased, never jumped: this map is the dot, so the camera follows it —
    // smoothly, because a camera that teleports under the reader's eyes is
    // the "shake" this file was rewritten to remove.
    map.easeTo({ center: lngLat, duration: 600 });
  };

  map.on('load', function () {
    loaded = true;
    window.__setPosition(pending);
  });
</script>
</body>
</html>`;
}

const HEIGHT = 150;

const styles = StyleSheet.create({
  frame: {
    height: HEIGHT,
    borderRadius: radius.md,
    overflow: 'hidden',
    backgroundColor: colors.surfaceSunken,
    marginTop: spacing.md,
  },
  web: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  placeholder: {
    height: HEIGHT,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceSunken,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
    marginTop: spacing.md,
  },
  placeholderText: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: 'center',
  },
  staleTag: {
    position: 'absolute',
    left: spacing.sm,
    bottom: spacing.sm,
    backgroundColor: colors.warningTint,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  staleTagText: {
    ...typography.caption,
    fontSize: 11,
    color: colors.warning,
  },
});
