/**
 * The vehicle, drawn from above — the same four silhouettes the office's live
 * map draws.
 *
 * ## Why the driver's own map has a car on it and not a dot
 *
 * This decision was already made once, on the other side of the platform.
 * `FleetMap` used to mark a unit with a coloured dot and a little arrow, and
 * the owner read the green dot as *"a dot where the vehicle should be"* — so
 * it became a top-down sprite, rotated to the reported heading, and the
 * comment there records why: **a map whose subject is vehicles should look
 * like it**. The driver app never got that decision and was still drawing its
 * own driver as a blue circle labelled "You".
 *
 * So this is a reuse, not a new idea. A dispatcher watching the fleet and the
 * driver watching themselves now see the same shape for the same thing, which
 * is the point of having one vocabulary at all.
 *
 * ## The copy, stated rather than hidden
 *
 * `frontend/public/assets/vehicles/*-top.svg` is the source of truth, and the
 * strings below are those files **verbatim** — generated by reading them, not
 * transcribed by eye, for the reason DESIGN.md §7 gives about Lucide paths.
 * Re-generate rather than hand-edit; a sprite that drifts from the console's
 * is worse than no sprite, because nobody will notice.
 *
 * They cannot be imported instead. Those live in a different bundle, and this
 * app's map is an inline WebView document with no asset pipeline in front of
 * it — which is also precisely what keeps it drawing in a dead zone, where a
 * fetched asset would leave a hole. The whole document is already built as a
 * string; one more string in it costs nothing at runtime.
 *
 * Only ever **one** sprite is inlined into a document — the driver's own
 * vehicle — which is what makes the shared `id="body"` / `id="glass"` defs
 * inside them safe. Two of these on one page would collide.
 */

/** The four top-down sprites, named as `frontend/src/lib/livePositions.ts` names them. */
export type VehicleSprite = 'sedan' | 'suv' | 'pickup' | 'boda';

/**
 * Category → silhouette.
 *
 * A deliberate transcription of `spriteKindFor` in
 * `frontend/src/lib/livePositions.ts`, which is itself the nearest-honest-shape
 * table the backend uses for the public read's `kind`. Kept identical on
 * purpose: a boda rider must not see themselves drawn as a saloon on one
 * screen and a rider on another.
 *
 * A tricycle takes the rider silhouette and a van the SUV's box because that
 * is as close as a four-sprite set gets. **An unknown or missing category
 * draws the sedan** — a generic car, which is a fallback rather than a claim
 * about what the driver is sitting in.
 */
const SPRITE_KINDS: Record<string, VehicleSprite> = {
  boda: 'boda',
  tricycle: 'boda',
  sedan: 'sedan',
  suv: 'suv',
  van: 'suv',
  minibus: 'suv',
  bus: 'suv',
  pickup: 'pickup',
  truck: 'pickup',
};

export function spriteFor(category: string | null | undefined): VehicleSprite {
  return SPRITE_KINDS[category ?? ''] ?? 'sedan';
}

/**
 * The sprite bodies, keyed by silhouette.
 *
 * Each is a complete `<svg>` element carrying only a `viewBox`, so the size is
 * the caller's to set in CSS — which is what the map document does, because a
 * marker's size is a property of the map and not of the vehicle.
 */
export const VEHICLE_SPRITES: Record<VehicleSprite, string> = {
  sedan: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- KangaruRide fleet · four-door sedan · true top-down · unified scale (1 unit shared across the set) -->
  <defs>
    <radialGradient id="shadow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#0B1220" stop-opacity="0.20"/>
      <stop offset="65%" stop-color="#0B1220" stop-opacity="0.10"/>
      <stop offset="100%" stop-color="#0B1220" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="body" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#D7DCE2"/>
      <stop offset="0.16" stop-color="#F4F6F8"/>
      <stop offset="0.5" stop-color="#FFFFFF"/>
      <stop offset="0.84" stop-color="#F4F6F8"/>
      <stop offset="1" stop-color="#D7DCE2"/>
    </linearGradient>
    <linearGradient id="glass" x1="0" y1="0" x2="0.7" y2="1">
      <stop offset="0" stop-color="#33383F"/>
      <stop offset="0.5" stop-color="#1D2025"/>
      <stop offset="1" stop-color="#111318"/>
    </linearGradient>
    <linearGradient id="green" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1CB964"/>
      <stop offset="1" stop-color="#118A48"/>
    </linearGradient>
  </defs>

  <ellipse cx="256" cy="258" rx="120" ry="216" fill="url(#shadow)"/>

  <!-- tires with a hint of alloy hub, peeking from under the body -->
  <g>
    <rect x="151" y="116" width="22" height="64" rx="10" fill="#17191C"/>
    <rect x="339" y="116" width="22" height="64" rx="10" fill="#17191C"/>
    <rect x="151" y="334" width="22" height="64" rx="10" fill="#17191C"/>
    <rect x="339" y="334" width="22" height="64" rx="10" fill="#17191C"/>
    <g fill="#8E969E">
      <rect x="156" y="136" width="5" height="24" rx="2.5"/>
      <rect x="351" y="136" width="5" height="24" rx="2.5"/>
      <rect x="156" y="354" width="5" height="24" rx="2.5"/>
      <rect x="351" y="354" width="5" height="24" rx="2.5"/>
    </g>
  </g>

  <!-- mirrors -->
  <rect x="142" y="148" width="30" height="15" rx="7" transform="rotate(-16 157 155)" fill="#EEF1F4"/>
  <rect x="340" y="148" width="30" height="15" rx="7" transform="rotate(16 355 155)" fill="#EEF1F4"/>

  <!-- body shell -->
  <path fill="url(#body)" d="M256 52 C305 52 336 65 340 116 L344 200 L344 330 L340 392 C336 440 306 460 256 460 C206 460 176 440 172 392 L168 330 L168 200 L172 116 C176 65 207 52 256 52 Z"/>

  <!-- panel seams -->
  <g stroke="#DDE2E7" stroke-width="3" fill="none" stroke-linecap="round">
    <path d="M176 206 L200 202"/>
    <path d="M336 206 L312 202"/>
    <path d="M172 288 L196 286"/>
    <path d="M340 288 L316 286"/>
    <path d="M186 414 C216 424 296 424 326 414"/>
    <path d="M190 92 C214 78 298 78 322 92"/>
  </g>

  <!-- windshield -->
  <path fill="url(#glass)" d="M190 138 C190 126 212 118 256 118 C300 118 322 126 322 138 L314 184 C312 194 292 199 256 199 C220 199 200 194 198 184 Z"/>

  <!-- panoramic roof -->
  <rect x="194" y="188" width="124" height="154" rx="28" fill="url(#glass)"/>

  <!-- roof gloss streak -->
  <path fill="#FFFFFF" opacity="0.07" d="M204 196 L240 192 L214 338 L200 320 Z"/>

  <!-- brand panel -->
  <rect x="223" y="220" width="66" height="90" rx="17" fill="url(#green)"/>
  <rect x="229" y="226" width="54" height="34" rx="12" fill="#FFFFFF" opacity="0.14"/>

  <!-- rear window -->
  <path fill="url(#glass)" d="M198 336 L314 336 C320 356 321 372 316 384 C300 393 212 393 196 384 C191 372 192 356 198 336 Z"/>
</svg>`,
  suv: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- KangaruRide fleet · compact SUV · true top-down · unified scale with sedan-top.svg -->
  <defs>
    <radialGradient id="shadow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#0B1220" stop-opacity="0.20"/>
      <stop offset="65%" stop-color="#0B1220" stop-opacity="0.10"/>
      <stop offset="100%" stop-color="#0B1220" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="body" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#D7DCE2"/>
      <stop offset="0.16" stop-color="#F4F6F8"/>
      <stop offset="0.5" stop-color="#FFFFFF"/>
      <stop offset="0.84" stop-color="#F4F6F8"/>
      <stop offset="1" stop-color="#D7DCE2"/>
    </linearGradient>
    <linearGradient id="glass" x1="0" y1="0" x2="0.7" y2="1">
      <stop offset="0" stop-color="#33383F"/>
      <stop offset="0.5" stop-color="#1D2025"/>
      <stop offset="1" stop-color="#111318"/>
    </linearGradient>
    <linearGradient id="green" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1CB964"/>
      <stop offset="1" stop-color="#118A48"/>
    </linearGradient>
  </defs>

  <ellipse cx="256" cy="256" rx="126" ry="210" fill="url(#shadow)"/>

  <!-- tires -->
  <g>
    <rect x="143" y="118" width="24" height="68" rx="11" fill="#17191C"/>
    <rect x="345" y="118" width="24" height="68" rx="11" fill="#17191C"/>
    <rect x="143" y="326" width="24" height="68" rx="11" fill="#17191C"/>
    <rect x="345" y="326" width="24" height="68" rx="11" fill="#17191C"/>
    <g fill="#8E969E">
      <rect x="148" y="140" width="5" height="26" rx="2.5"/>
      <rect x="358" y="140" width="5" height="26" rx="2.5"/>
      <rect x="148" y="348" width="5" height="26" rx="2.5"/>
      <rect x="358" y="348" width="5" height="26" rx="2.5"/>
    </g>
  </g>

  <!-- mirrors -->
  <rect x="134" y="152" width="32" height="16" rx="8" transform="rotate(-16 150 160)" fill="#EEF1F4"/>
  <rect x="346" y="152" width="32" height="16" rx="8" transform="rotate(16 362 160)" fill="#EEF1F4"/>

  <!-- body shell: boxier, fuller rear than the sedan -->
  <path fill="url(#body)" d="M256 60 C306 60 342 72 346 122 L350 210 L350 350 L348 404 C344 442 310 452 256 452 C202 452 168 442 164 404 L162 350 L162 210 L166 122 C170 72 206 60 256 60 Z"/>

  <!-- panel seams -->
  <g stroke="#DDE2E7" stroke-width="3" fill="none" stroke-linecap="round">
    <path d="M168 208 L194 205"/>
    <path d="M344 208 L318 205"/>
    <path d="M166 296 L192 294"/>
    <path d="M346 296 L320 294"/>
    <path d="M182 420 C214 430 298 430 330 420"/>
    <path d="M186 100 C212 86 300 86 326 100"/>
  </g>

  <!-- windshield: more upright than the sedan, so shorter in plan -->
  <path fill="url(#glass)" d="M188 142 C188 130 212 123 256 123 C300 123 324 130 324 142 L318 178 C316 188 294 193 256 193 C218 193 196 188 194 178 Z"/>

  <!-- long panoramic roof, running close to the tailgate -->
  <rect x="188" y="182" width="136" height="188" rx="30" fill="url(#glass)"/>

  <!-- roof rails -->
  <rect x="180" y="192" width="9" height="168" rx="4.5" fill="#2A2E33"/>
  <rect x="323" y="192" width="9" height="168" rx="4.5" fill="#2A2E33"/>

  <!-- roof gloss streak -->
  <path fill="#FFFFFF" opacity="0.07" d="M200 192 L238 188 L212 366 L196 344 Z"/>

  <!-- brand panel -->
  <rect x="222" y="230" width="68" height="94" rx="17" fill="url(#green)"/>
  <rect x="228" y="236" width="56" height="36" rx="12" fill="#FFFFFF" opacity="0.14"/>

  <!-- tailgate window: short and steep -->
  <path fill="url(#glass)" d="M196 366 L316 366 C321 380 321 390 317 398 C298 406 214 406 195 398 C191 390 191 380 196 366 Z"/>
</svg>`,
  pickup: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- KangaruRide fleet · double-cabin pickup · true top-down · unified scale with sedan-top.svg -->
  <defs>
    <radialGradient id="shadow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#0B1220" stop-opacity="0.20"/>
      <stop offset="65%" stop-color="#0B1220" stop-opacity="0.10"/>
      <stop offset="100%" stop-color="#0B1220" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="body" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#D7DCE2"/>
      <stop offset="0.16" stop-color="#F4F6F8"/>
      <stop offset="0.5" stop-color="#FFFFFF"/>
      <stop offset="0.84" stop-color="#F4F6F8"/>
      <stop offset="1" stop-color="#D7DCE2"/>
    </linearGradient>
    <linearGradient id="glass" x1="0" y1="0" x2="0.7" y2="1">
      <stop offset="0" stop-color="#33383F"/>
      <stop offset="0.5" stop-color="#1D2025"/>
      <stop offset="1" stop-color="#111318"/>
    </linearGradient>
    <linearGradient id="green" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1CB964"/>
      <stop offset="1" stop-color="#118A48"/>
    </linearGradient>
    <linearGradient id="bed" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#33383E"/>
      <stop offset="1" stop-color="#262A2F"/>
    </linearGradient>
  </defs>

  <ellipse cx="256" cy="256" rx="124" ry="228" fill="url(#shadow)"/>

  <!-- tires: rear pair set wide for the workhorse stance -->
  <g>
    <rect x="145" y="104" width="24" height="68" rx="11" fill="#17191C"/>
    <rect x="343" y="104" width="24" height="68" rx="11" fill="#17191C"/>
    <rect x="143" y="330" width="26" height="72" rx="12" fill="#17191C"/>
    <rect x="343" y="330" width="26" height="72" rx="12" fill="#17191C"/>
    <g fill="#8E969E">
      <rect x="150" y="126" width="5" height="26" rx="2.5"/>
      <rect x="356" y="126" width="5" height="26" rx="2.5"/>
      <rect x="148" y="354" width="5" height="26" rx="2.5"/>
      <rect x="358" y="354" width="5" height="26" rx="2.5"/>
    </g>
  </g>

  <!-- mirrors: larger, truck-style -->
  <rect x="132" y="140" width="34" height="17" rx="8" transform="rotate(-16 149 148)" fill="#EEF1F4"/>
  <rect x="346" y="140" width="34" height="17" rx="8" transform="rotate(16 363 148)" fill="#EEF1F4"/>

  <!-- body shell: long, slab-sided, square tail -->
  <path fill="url(#body)" d="M256 46 C304 46 340 58 344 108 L348 190 L348 400 C348 442 322 466 256 466 C190 466 164 442 164 400 L164 190 L168 108 C172 58 208 46 256 46 Z"/>

  <!-- panel seams -->
  <g stroke="#DDE2E7" stroke-width="3" fill="none" stroke-linecap="round">
    <path d="M170 196 L196 193"/>
    <path d="M342 196 L316 193"/>
    <path d="M168 268 L194 266"/>
    <path d="M344 268 L318 266"/>
    <path d="M186 86 C212 72 300 72 326 86"/>
  </g>

  <!-- windshield -->
  <path fill="url(#glass)" d="M190 128 C190 116 212 109 256 109 C300 109 322 116 322 128 L316 164 C314 174 292 179 256 179 C220 179 198 174 196 164 Z"/>

  <!-- double-cab roof -->
  <rect x="190" y="168" width="132" height="124" rx="26" fill="url(#glass)"/>

  <!-- roof gloss streak -->
  <path fill="#FFFFFF" opacity="0.07" d="M202 176 L238 172 L214 286 L198 268 Z"/>

  <!-- brand panel -->
  <rect x="224" y="192" width="64" height="76" rx="16" fill="url(#green)"/>
  <rect x="230" y="198" width="52" height="30" rx="11" fill="#FFFFFF" opacity="0.14"/>

  <!-- rear cab glass -->
  <path fill="url(#glass)" d="M198 288 L314 288 C317 296 317 302 314 308 C296 314 216 314 198 308 C195 302 195 296 198 288 Z"/>

  <!-- cargo bed -->
  <rect x="186" y="322" width="140" height="122" rx="14" fill="url(#bed)"/>
  <!-- bed ribs -->
  <g stroke="#3B4046" stroke-width="4" stroke-linecap="round">
    <line x1="196" y1="342" x2="316" y2="342"/>
    <line x1="196" y1="362" x2="316" y2="362"/>
    <line x1="196" y1="382" x2="316" y2="382"/>
    <line x1="196" y1="402" x2="316" y2="402"/>
    <line x1="196" y1="422" x2="316" y2="422"/>
  </g>
  <!-- tailgate seam -->
  <path d="M186 448 C216 456 296 456 326 448" stroke="#DDE2E7" stroke-width="3" fill="none" stroke-linecap="round"/>
</svg>`,
  boda: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- KangaruRide fleet · boda boda with rider · true top-down · unified scale with sedan-top.svg -->
  <defs>
    <radialGradient id="shadow" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#0B1220" stop-opacity="0.20"/>
      <stop offset="65%" stop-color="#0B1220" stop-opacity="0.10"/>
      <stop offset="100%" stop-color="#0B1220" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="green" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#128A48"/>
      <stop offset="0.5" stop-color="#1CB964"/>
      <stop offset="1" stop-color="#128A48"/>
    </linearGradient>
    <linearGradient id="jacket" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1CB964"/>
      <stop offset="1" stop-color="#0F7A40"/>
    </linearGradient>
    <linearGradient id="steel" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#9AA1A8"/>
      <stop offset="0.5" stop-color="#C7CDD3"/>
      <stop offset="1" stop-color="#9AA1A8"/>
    </linearGradient>
    <radialGradient id="helmet" cx="38%" cy="32%" r="75%">
      <stop offset="0" stop-color="#3A3F45"/>
      <stop offset="0.55" stop-color="#22252A"/>
      <stop offset="1" stop-color="#141619"/>
    </radialGradient>
  </defs>

  <ellipse cx="256" cy="258" rx="70" ry="132" fill="url(#shadow)"/>

  <!-- wheels -->
  <rect x="248" y="138" width="16" height="60" rx="8" fill="#17191C"/>
  <rect x="248" y="336" width="16" height="42" rx="8" fill="#17191C"/>

  <!-- forks -->
  <rect x="244" y="166" width="5" height="44" rx="2.5" fill="url(#steel)"/>
  <rect x="263" y="166" width="5" height="44" rx="2.5" fill="url(#steel)"/>

  <!-- front fender -->
  <rect x="245" y="136" width="22" height="34" rx="11" fill="url(#green)"/>

  <!-- rear carrier rack -->
  <rect x="236" y="342" width="40" height="32" rx="8" fill="#26292E"/>
  <g stroke="#3B4046" stroke-width="4" stroke-linecap="round">
    <line x1="244" y1="352" x2="268" y2="352"/>
    <line x1="244" y1="362" x2="268" y2="362"/>
  </g>

  <!-- engine block -->
  <rect x="235" y="256" width="42" height="42" rx="9" fill="url(#steel)"/>

  <!-- fuel tank -->
  <path fill="url(#green)" d="M256 206 C274 206 282 216 282 232 C282 248 274 258 256 258 C238 258 230 248 230 232 C230 216 238 206 256 206 Z"/>
  <ellipse cx="250" cy="220" rx="12" ry="7" fill="#FFFFFF" opacity="0.18"/>

  <!-- seat (tail visible behind the rider) -->
  <rect x="233" y="296" width="46" height="48" rx="15" fill="#1D2024"/>

  <!-- handlebar, grips, mirrors -->
  <g stroke="#4A5057" stroke-width="4" stroke-linecap="round">
    <line x1="212" y1="200" x2="200" y2="182"/>
    <line x1="300" y1="200" x2="312" y2="182"/>
  </g>
  <circle cx="198" cy="178" r="8" fill="#26292E"/>
  <circle cx="314" cy="178" r="8" fill="#26292E"/>
  <rect x="201" y="197" width="110" height="11" rx="5.5" fill="#26292E"/>

  <!-- rider legs: black trousers, knees out, boots on the pegs -->
  <rect x="207" y="272" width="17" height="58" rx="8.5" transform="rotate(14 215 301)" fill="#17191C"/>
  <rect x="288" y="272" width="17" height="58" rx="8.5" transform="rotate(-14 296 301)" fill="#17191C"/>
  <rect x="197" y="320" width="22" height="15" rx="7" transform="rotate(10 208 327)" fill="#0E1013"/>
  <rect x="293" y="320" width="22" height="15" rx="7" transform="rotate(-10 304 327)" fill="#0E1013"/>

  <!-- rider arms reaching the grips, black gloves -->
  <rect x="214" y="210" width="16" height="82" rx="8" transform="rotate(18 222 251)" fill="url(#jacket)"/>
  <rect x="282" y="210" width="16" height="82" rx="8" transform="rotate(-18 290 251)" fill="url(#jacket)"/>
  <circle cx="213" cy="204" r="9" fill="#0E1013"/>
  <circle cx="299" cy="204" r="9" fill="#0E1013"/>

  <!-- rider torso: green jacket, seated behind the tank so it stays visible -->
  <path fill="url(#jacket)" d="M256 256 C280 256 293 268 293 288 L289 334 C287 350 273 356 256 356 C239 356 225 350 223 334 L219 288 C219 268 232 256 256 256 Z"/>
  <path fill="#FFFFFF" opacity="0.10" d="M233 266 C244 260 268 260 279 266 C282 272 280 278 275 280 C262 274 250 274 237 280 C232 278 230 272 233 266 Z"/>

  <!-- helmet -->
  <circle cx="256" cy="286" r="24" fill="url(#helmet)"/>
  <path fill="#FFFFFF" opacity="0.10" d="M241 274 C247 266 265 266 271 274 C267 270 245 270 241 274 Z"/>
</svg>`,
};
